<?xml version="1.0"?>
<robot>  
 
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>false</alwaysOn>
      <legacyMode>false</legacyMode>
      <updateRate>20</updateRate>
      <leftJoint>left_f_wheel_joint</leftJoint>
      <rightJoint>right_f_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>/minion/cmd_vel</commandTopic>
      <odometryTopic>/minion/odom</odometryTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <publishWheelJointState>true</publishWheelJointState>
      <rosDebugLevel>na</rosDebugLevel>
      <wheelTorque>10</wheelTorque>
      <wheelAcceleration>1</wheelAcceleration>
      <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
    </plugin>
  </gazebo>
 
</robot>